import { createCipheriv, createDecipheriv, createHash, randomBytes } from "node:crypto";
import type { NextFunction, Request, Response } from "express";
import type { AppEnvironment } from "../config/env";
import { AppError } from "../http/error";
const isExcluded = (path: string) => path === "/api/health" || path.startsWith("/api/docs") || path.startsWith("/api/openapi");
const keyFor = (environment: AppEnvironment) => createHash("sha256").update(environment.API_ENCRYPTION_KEY ?? "").digest();
function encrypt(value: unknown, environment: AppEnvironment) { const iv = randomBytes(12); const cipher = createCipheriv("aes-256-gcm", keyFor(environment), iv); const ciphertext = Buffer.concat([cipher.update(JSON.stringify(value), "utf8"), cipher.final()]); return Buffer.concat([iv, cipher.getAuthTag(), ciphertext]).toString("base64"); }
function decrypt(payload: string, environment: AppEnvironment) { const data = Buffer.from(payload, "base64"); if (data.length < 29) throw new AppError("Invalid encrypted payload", 400, "INVALID_ENCRYPTED_PAYLOAD"); const decipher = createDecipheriv("aes-256-gcm", keyFor(environment), data.subarray(0, 12)); decipher.setAuthTag(data.subarray(12, 28)); return JSON.parse(Buffer.concat([decipher.update(data.subarray(28)), decipher.final()]).toString("utf8")); }
export function requestDecryption(environment: AppEnvironment) { return (request: Request, _response: Response, next: NextFunction) => { if (!environment.API_ENCRYPTION_ENABLED || isExcluded(request.path) || ["GET", "HEAD"].includes(request.method)) return next(); try { const encryptedData = request.body?.encryptedData; if (typeof encryptedData !== "string") throw new AppError("Encrypted request body is required", 400, "ENCRYPTION_REQUIRED"); request.body = decrypt(encryptedData, environment); next(); } catch (error) { next(error instanceof AppError ? error : new AppError("Invalid encrypted payload", 400, "INVALID_ENCRYPTED_PAYLOAD")); } }; }
export function responseEncryption(environment: AppEnvironment) { return (request: Request, response: Response, next: NextFunction) => { if (!environment.API_ENCRYPTION_ENABLED || isExcluded(request.path)) return next(); const originalJson = response.json.bind(response); response.json = ((body: unknown) => { response.setHeader("X-Payload-Encrypted", "true"); return originalJson({ encryptedData: encrypt(body, environment) }); }) as Response["json"]; next(); }; }
