import { AppstoreOutlined, BankOutlined, CustomerServiceOutlined, FileTextOutlined, HomeOutlined, LogoutOutlined, SafetyCertificateOutlined, SettingOutlined, TeamOutlined, TransactionOutlined } from "@ant-design/icons";
import { Avatar, Button, Dropdown, Layout, Menu, Space, Typography } from "antd";
import type { MenuProps } from "antd";
import { useEffect, useState } from "react";
import { Link, Outlet, useLocation, useNavigate } from "react-router-dom";
import { clearSession, getSession, sessionChangedEvent } from "../auth/session";
const { Header, Sider, Content } = Layout;

function ProtectedShell({ title, items }: { title: string; items: MenuProps["items"] }) { const location = useLocation(); const navigate = useNavigate(); const session = getSession(); return <Layout className="app-shell"><Sider breakpoint="lg" collapsedWidth="0" className="app-sider"><Link className="brand" to="/"><img src="/certificate-chain-logo.png" alt="Certificate Chain" />Certificate Chain</Link><Menu theme="dark" mode="inline" selectedKeys={[location.pathname]} items={items} onClick={({ key }) => navigate(key)} /></Sider><Layout><Header className="app-header"><Typography.Text strong>{title}</Typography.Text><Dropdown menu={{ items: [{ key: "home", icon: <HomeOutlined />, label: "Trang chủ", onClick: () => navigate("/") }, { key: "logout", icon: <LogoutOutlined />, label: "Đăng xuất", onClick: () => { clearSession(); navigate("/login"); } }] }}><Button type="text"><Space><Avatar size="small">{session?.fullName?.slice(0, 1) ?? "U"}</Avatar>{session?.fullName ?? session?.role}</Space></Button></Dropdown></Header><Content className="app-content"><Outlet /></Content></Layout></Layout>; }
export function AdminLayout() { return <ProtectedShell title="Cổng quản trị" items={[{ key: "/admin/dashboard", icon: <AppstoreOutlined />, label: "Tổng quan" }, { key: "/admin/students", icon: <TeamOutlined />, label: "Sinh viên" }, { key: "/admin/institutions", icon: <BankOutlined />, label: "Cơ sở đào tạo" }, { key: "/admin/academics", icon: <FileTextOutlined />, label: "Ngành, khóa, lớp" }, { key: "/admin/certificates", icon: <SafetyCertificateOutlined />, label: "Văn bằng" }, { key: "/admin/blockchain-transactions", icon: <TransactionOutlined />, label: "Giao dịch Blockchain" }, { key: "/admin/consultations", icon: <CustomerServiceOutlined />, label: "Yêu cầu tư vấn" }, { key: "/admin/advanced-settings", icon: <SettingOutlined />, label: "Cài đặt nâng cao" }]} />; }
export function StudentLayout() { return <ProtectedShell title="Cổng sinh viên" items={[{ key: "/student/certificates", icon: <FileTextOutlined />, label: "Văn bằng của tôi" }]} />; }
export function PublicLayout() { const location = useLocation(); const navigate = useNavigate(); const [session, setSession] = useState(getSession()); useEffect(() => { const refresh = () => setSession(getSession()); window.addEventListener(sessionChangedEvent, refresh); return () => window.removeEventListener(sessionChangedEvent, refresh); }, []); const userMenu = session ? [{ key: "home", icon: <HomeOutlined />, label: "Trang chủ", onClick: () => navigate("/") }, { key: "portal", icon: session.role === "ADMIN" ? <AppstoreOutlined /> : <FileTextOutlined />, label: session.role === "ADMIN" ? "Cổng quản trị" : "Văn bằng của tôi", onClick: () => navigate(session.role === "ADMIN" ? "/admin/dashboard" : "/student/certificates") }, { type: "divider" as const }, { key: "logout", icon: <LogoutOutlined />, label: "Đăng xuất", onClick: () => { clearSession(); navigate("/login"); } }] : []; return <Layout className="public-shell"><Header className="public-header"><div className="public-header-inner"><Link className="brand dark-brand" to="/"><img src="/certificate-chain-logo.png" alt="Certificate Chain" /><span>Certificate Chain<small>Xác thực văn bằng số</small></span></Link><nav className="public-nav" aria-label="Điều hướng công khai"><Link to="/">Trang chủ</Link><Link className={location.pathname.startsWith("/verify") ? "active" : ""} to="/verify">Tra cứu</Link><Link className={location.pathname === "/features" ? "active" : ""} to="/features">Tính năng</Link><Link className={location.pathname === "/process" ? "active" : ""} to="/process">Quy trình</Link><Link className={location.pathname === "/contact" ? "active" : ""} to="/contact">Liên hệ</Link></nav>{session ? <Dropdown menu={{ items: userMenu }}><Button className="public-user-button" type="text"><Avatar size="small">{session.fullName?.slice(0, 1) ?? "U"}</Avatar>{session.fullName ?? session.email}</Button></Dropdown> : <Link className="public-login-link" to="/login">Đăng nhập</Link>}</div></Header><Content className={["/verify", "/features", "/contact", "/process"].includes(location.pathname) ? "public-content public-lookup-content" : "public-content"}><Outlet /></Content></Layout>; }
